### ISSUE TITLE
Calling stopScan during scanning causes an error

### ISSUE THREAD

**Issue by ghost** [evothings/cordova-eddystone#4]
Report from user:

"I have been playing with the eddystone plugin in ionic.

I am a little confused about the following two statements:

startScan will keep scanning until you call stopScan().

To conserve energy, call stopScan() as soon as you've found the device you're looking for. Calling this function while scanning is in progress will produce an error

As I understand these two statements, because startScan scans continuously then stopScan will always cause an error.

In practice i observe that calling stopScan after startScan is running, does indeed show an error "Scanning already in progress!", and the beacon scanning continues.

Therefore how do we programatically stop beacon scanning ?"

**Comment by ghost** [comment]
Did a test app to verify problem with stopScan: https://github.com/mikaelkindborg/evo-demos/tree/master/Demos2016/eddystone-test

Could not reproduce this problem. Perhaps the code originally reported to demonstrate the error mistakenly called startScan instead of stopScan, which would produce the "Scanning already in progress!" error.

**Comment by tomkelsey** [comment]
Hi @mikaelkindborg,

I was a little confused by the readme and wonder whether the user behind this issue got a bit muddled too. The paragraph I'm referring to is:

'To conserve energy, call stopScan() as soon as you've found the device you're looking for. Calling this function while scanning is in progress will produce an error.'

I think it would be clearer if it read:

'To conserve energy, call stopScan() as soon as you've found the device you're looking for.
Calling startScan() while scanning is in progress will produce an error.'

Otherwise on first glance it looks as if 'this function' refers to stopScan() rather than startScan()

Hope that makes sense!

**Comment by ghost** [comment]
@tomkelsey Thanks for the clarification! Will update the comment!
